### ISSUE TITLE
Didn't work with YAML

### ISSUE THREAD

**Issue by kusmayadi** [nektos/act#80] opened 2019-10-22 08:50 UTC
It didn't work with the new yaml syntax (https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions). 

When running `act -f .github/workflows/main.yml -l`, I got: 

```
Error: unable to parse
  Line 1: illegal char
```

**Comment by finalspy** [comment] 2019-10-22 14:15
Isn't it a duplicate of #74 and #76 ?

**Closed** 2020-02-12 08:23 UTC
Labels: duplicate
