### ISSUE TITLE
Provide more specific error message when Docker is not running

### ISSUE THREAD

**Issue by MisterJimson** [nektos/act#199] opened 2020-04-17 18:33 UTC
Just installed `act` and tried it out.

Got this error `Error: unable to determine if image already exists for image "node:12.6-buster-slim"`

Turns out Docker wasn't running. Perhaps we check if Docker is running and display a more specific error message.

**Comment by cplee** [comment] 2020-04-17 18:50
duplicate of #168

**Closed by cplee** 2020-04-17 18:50 UTC
