### ISSUE TITLE
Dry run results in RTE for a simple workflow & custom action.

### ISSUE THREAD

**Issue by thetownfool** [nektos/act#1185] opened 2022-05-26 20:05 UTC
### Bug report info

act version:            0.2.26
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:
	/Users/carl/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Docker Engine:
	Engine version:        20.10.8
	Engine runtime:        runc
	Cgroup version:        1
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:
	OS arch:               x86_64
	OS kernel:             5.10.47-linuxkit
	OS CPU:                4
	OS memory:             1985 MB
	Security options:
		name=seccomp,profile=default

### Command used with act

```sh
act -n
```

### Describe issue

dry-run results in runtime exception:

```shell

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x71 pc=0x164e10e]

goroutine 5 [running]:
github.com/docker/docker/client.(*Client).getAPIPath(0xc0003ebb90?, {0x19841f8?, 0xc0004337a0?}, {0xc0000f33c0, 0x14}, 0x14?)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/client.go:183 +0x4e
github.com/docker/docker/client.(*Client).sendRequest(0x1856eb7?, {0x19841f8, 0xc0004337a0}, {0x18568aa, 0x3}, {0xc0000f33c0?, 0x80000000a?}, 0x49249249249249?, {0x0, 0x0}, ...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/request.go:109 +0x78
github.com/docker/docker/client.(*Client).get(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/request.go:37
github.com/docker/docker/client.(*Client).CopyFromContainer(0x56?, {0x19841f8, 0xc0004337a0}, {0x0, 0x0}, {0xc0004800c0, 0x56})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/container_copy.go:68 +0x1fe
github.com/nektos/act/pkg/container.(*containerReference).GetContainerArchive(0xc0000f3798?, {0x19841f8?, 0xc0004337a0?}, {0xc0004800c0?, 0xc0000f37a0?})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/container/docker_run.go:164 +0x59
github.com/nektos/act/pkg/runner.(*StepContext).Executor.func1.1({0x185a42b?, 0xc0000f3888?})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/step_context.go:70 +0xbc
github.com/nektos/act/pkg/runner.(*StepContext).readAction(0x19841f8?, 0xc0001e3500, {0xc00016fcc0, 0x4b}, {0x0, 0x0}, 0xc00010ebd0, 0x18b2898)
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/action.go:25 +0x9c
github.com/nektos/act/pkg/runner.(*StepContext).setupAction.func1({0x19841f8?, 0xc0004337a0?})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/step_context.go:387 +0x9f
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc0004337a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:131 +0x34
github.com/nektos/act/pkg/runner.(*RunContext).newStepExecutor.func1({0x19841f8, 0xc0004337a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/run_context.go:360 +0x350
github.com/nektos/act/pkg/runner.newJobExecutor.func2.1(0x19841f8?, {0x19841f8, 0xc0004337a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/job_executor.go:42 +0x36
github.com/nektos/act/pkg/runner.newJobExecutor.func2({0x19841f8?, 0xc00010e2a0?})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/job_executor.go:51 +0x8d
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc00010e2a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:143 +0xe4
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc00010e2a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:131 +0x34
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc00010e2a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:131 +0x34
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc00010e2a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:131 +0x34
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x19841f8, 0xc00010e2a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:177 +0x34
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x19841f8, 0xc00010e2a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:177 +0x34
github.com/nektos/act/pkg/runner.(*RunContext).Executor.func1({0x19841f8, 0xc00010e2a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/run_context.go:290 +0x67
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x19841f8, 0xc00010e2a0})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:177 +0x34
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1.1({0x19841f8, 0xc000432450})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/runner.go:171 +0x2f2
github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1(0x0?, 0x0?)
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:102 +0x5c
created by github.com/nektos/act/pkg/common.NewParallelExecutor.func1
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:100 +0x89
```

### Link to GitHub repository

https://github.com/thetownfool/act-error-example

### Workflow content

```yml
name: Sample Workflow
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Build Step 1'
        uses: ./.github/actions/mock
        with:
          MOCK_STEP_NAME: "Build Step 1"
```

### Relevant log output

```sh
DEBU[0000] Loading environment from /Users/carl/Documents/Develop.nosync/act-error-example/.env
DEBU[0000] Loading secrets from /Users/carl/Documents/Develop.nosync/act-error-example/.secrets
DEBU[0000] Loading workflows from '/Users/carl/Documents/Develop.nosync/act-error-example/.github/workflows'
DEBU[0000] Loading workflows recursively
DEBU[0000] Found workflow 'main.yml' in '/Users/carl/Documents/Develop.nosync/act-error-example/.github/workflows/main.yml'
DEBU[0000] Reading workflow '/Users/carl/Documents/Develop.nosync/act-error-example/.github/workflows/main.yml'
DEBU[0000] Planning event: push
DEBU[0000] Loading slug from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Loading revision from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] HEAD points to '2da40cef434ed57ba3de4680a34d9972be7e357b'
DEBU[0000] using github ref: refs/heads/main
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] evaluating expression 'success()'
DEBU[0000] expression 'success()' evaluated to 'true'
*DRYRUN* [Sample Workflow/Build] 🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
DEBU[0000] Loading slug from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Loading revision from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] HEAD points to '2da40cef434ed57ba3de4680a34d9972be7e357b'
DEBU[0000] using github ref: refs/heads/main
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
*DRYRUN* [Sample Workflow/Build]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=false
*DRYRUN* [Sample Workflow/Build]   🐳  docker pull ghcr.io/catthehacker/ubuntu:act-latest
*DRYRUN* [Sample Workflow/Build]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
*DRYRUN* [Sample Workflow/Build]   🐳  docker run image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
DEBU[0000] Loading slug from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Loading revision from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] HEAD points to '2da40cef434ed57ba3de4680a34d9972be7e357b'
DEBU[0000] using github ref: refs/heads/main
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] evaluating expression ''
DEBU[0000] expression '' evaluated to 'true'
DEBU[0000] Loading slug from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Loading revision from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] HEAD points to '2da40cef434ed57ba3de4680a34d9972be7e357b'
DEBU[0000] using github ref: refs/heads/main
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] Loading slug from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Loading revision from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] HEAD points to '2da40cef434ed57ba3de4680a34d9972be7e357b'
DEBU[0000] using github ref: refs/heads/main
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
*DRYRUN* [Sample Workflow/Build] setupEnv => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_PATH: GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:Build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/main GITHUB_REPOSITORY:thetownfool/act-error-example GITHUB_REPOSITORY_OWNER:thetownfool GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:2da40cef434ed57ba3de4680a34d9972be7e357b GITHUB_TOKEN: GITHUB_WORKFLOW:Sample Workflow GITHUB_WORKSPACE:/Users/carl/Documents/Develop.nosync/act-error-example ImageOS:ubuntu20 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID:]
*DRYRUN* [Sample Workflow/Build] ⭐  Run Checkout
DEBU[0000] Loading slug from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Loading revision from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] HEAD points to '2da40cef434ed57ba3de4680a34d9972be7e357b'
DEBU[0000] using github ref: refs/heads/main
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
*DRYRUN* [Sample Workflow/Build] Skipping local actions/checkout because workdir was already copied
*DRYRUN* [Sample Workflow/Build]   ✅  Success - Checkout
DEBU[0000] Loading slug from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Loading revision from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] HEAD points to '2da40cef434ed57ba3de4680a34d9972be7e357b'
DEBU[0000] using github ref: refs/heads/main
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] evaluating expression ''
DEBU[0000] expression '' evaluated to 'true'
DEBU[0000] Loading slug from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Loading revision from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] HEAD points to '2da40cef434ed57ba3de4680a34d9972be7e357b'
DEBU[0000] using github ref: refs/heads/main
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] Loading slug from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Loading revision from git directory '/Users/carl/Documents/Develop.nosync/act-error-example/.git'
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
DEBU[0000] HEAD points to '2da40cef434ed57ba3de4680a34d9972be7e357b'
DEBU[0000] using github ref: refs/heads/main
DEBU[0000] Found revision: 2da40cef434ed57ba3de4680a34d9972be7e357b
*DRYRUN* [Sample Workflow/Build] setupEnv => map[ACT:true CI:true GITHUB_ACTION:1 GITHUB_ACTIONS:true GITHUB_ACTION_PATH: GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:Build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/main GITHUB_REPOSITORY:thetownfool/act-error-example GITHUB_REPOSITORY_OWNER:thetownfool GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:2da40cef434ed57ba3de4680a34d9972be7e357b GITHUB_TOKEN: GITHUB_WORKFLOW:Sample Workflow GITHUB_WORKSPACE:/Users/carl/Documents/Develop.nosync/act-error-example INPUT_MOCK_STEP_NAME:Build Step 1 ImageOS:ubuntu20 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID:]
*DRYRUN* [Sample Workflow/Build] ⭐  Run Build Step 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x71 pc=0x164e10e]

goroutine 22 [running]:
github.com/docker/docker/client.(*Client).getAPIPath(0xc0000c6ac0?, {0x19841f8?, 0xc000426750?}, {0xc0001293c0, 0x14}, 0x14?)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/client.go:183 +0x4e
github.com/docker/docker/client.(*Client).sendRequest(0x1856eb7?, {0x19841f8, 0xc000426750}, {0x18568aa, 0x3}, {0xc0001293c0?, 0x80000000a?}, 0x49249249249249?, {0x0, 0x0}, ...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/request.go:109 +0x78
github.com/docker/docker/client.(*Client).get(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/request.go:37
github.com/docker/docker/client.(*Client).CopyFromContainer(0x56?, {0x19841f8, 0xc000426750}, {0x0, 0x0}, {0xc00010f620, 0x56})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/container_copy.go:68 +0x1fe
github.com/nektos/act/pkg/container.(*containerReference).GetContainerArchive(0xc000129798?, {0x19841f8?, 0xc000426750?}, {0xc00010f620?, 0xc0001297a0?})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/container/docker_run.go:164 +0x59
github.com/nektos/act/pkg/runner.(*StepContext).Executor.func1.1({0x185a42b?, 0xc000129888?})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/step_context.go:70 +0xbc
github.com/nektos/act/pkg/runner.(*StepContext).readAction(0x19841f8?, 0xc0001a1500, {0xc000459d60, 0x4b}, {0x0, 0x0}, 0xc0005124b0, 0x18b2898)
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/action.go:25 +0x9c
github.com/nektos/act/pkg/runner.(*StepContext).setupAction.func1({0x19841f8?, 0xc000426750?})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/step_context.go:387 +0x9f
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc000426750})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:131 +0x34
github.com/nektos/act/pkg/runner.(*RunContext).newStepExecutor.func1({0x19841f8, 0xc000426750})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/run_context.go:360 +0x350
github.com/nektos/act/pkg/runner.newJobExecutor.func2.1(0x19841f8?, {0x19841f8, 0xc000426750})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/job_executor.go:42 +0x36
github.com/nektos/act/pkg/runner.newJobExecutor.func2({0x19841f8?, 0xc0000ca300?})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/job_executor.go:51 +0x8d
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc0000ca300})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:143 +0xe4
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc0000ca300})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:131 +0x34
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc0000ca300})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:131 +0x34
github.com/nektos/act/pkg/common.Executor.Then.func1({0x19841f8, 0xc0000ca300})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:131 +0x34
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x19841f8, 0xc0000ca300})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:177 +0x34
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x19841f8, 0xc0000ca300})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:177 +0x34
github.com/nektos/act/pkg/runner.(*RunContext).Executor.func1({0x19841f8, 0xc0000ca300})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/run_context.go:290 +0x67
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x19841f8, 0xc0000ca300})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:177 +0x34
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1.1({0x19841f8, 0xc0003e8750})
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/runner.go:171 +0x2f2
github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1(0x0?, 0x0?)
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:102 +0x5c
created by github.com/nektos/act/pkg/common.NewParallelExecutor.func1
	/private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:100 +0x89
```

**Comment by ChristopherHX** [comment] 2022-05-29 20:12
This is a duplicate of https://github.com/nektos/act/issues/1140, RTE fixed by https://github.com/nektos/act/pull/1141.
`uses: ./.github/actions/mock` will result in a file not found error, I'm not shure how local actions should be handled in a DRYRUN.

**Closed by ChristopherHX** 2022-05-29 20:12 UTC
Labels: kind/bug
