### ISSUE TITLE
[Duplicate] Consider publishing act to winget packages repository

### ISSUE THREAD

**Issue by rrmistry** [nektos/act#1489] opened 2022-12-02 06:07 UTC
### Act version

act version 0.2.34

### Feature description

This is a duplicate of issue #253.

Just thought to create this issue to raise attention since the original issue was closed by a bot.

The blocker that the issue was waiting on (i.e. https://github.com/microsoft/winget-cli/issues/140) has since been resolved (i.e. https://github.com/microsoft/winget-cli/pull/2500).

Instructions on how to support `winget` seem to be found here [Authoring Manifests](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md).

But need some help to dig further.

CC: @rodrigoscna, @rodrigoscna, @chrpai

**Comment by cmjchrisjones** [comment] 2023-01-12 00:07
I was just searching to see if Winget was available, 🤞 it gets considered :)

**Comment by sitiom** [comment] 2023-02-01 06:43
Duplicate of #1146

**Comment by sitiom** [comment] 2023-02-10 15:54
PR is merged. Please close this now.

**Closed** 2023-02-11 18:25 UTC
Labels: kind/feature-request
