### ISSUE TITLE
Enhancement: node16 support

### ISSUE THREAD

**Issue by cmeissner** [nektos/act#961] opened 2022-01-21 09:47 UTC
## Describe feature

I want to use `act` with a javascript action that uses node16. Unfortunately `act` currently only support node12 

```
Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16
```

**Comment by catthehacker** [comment] 2022-01-21 10:16
Duplicate of #910

**Closed by catthehacker** 2022-01-21 10:16 UTC
Labels: kind/feature-request
