### ISSUE TITLE
Can not start python environment in MacOS

### ISSUE THREAD

**Issue by magiskboy** [nektos/act#388] opened 2020-10-12 02:18 UTC
I run `act push -j fastapi`, then I got a error

<img width="1420" alt="Screen Shot 2020-10-12 at 09 15 45" src="https://user-images.githubusercontent.com/13352088/95698311-b73a0900-0c6b-11eb-8396-c72f5eb67558.png">

This is the action file 

```yaml
name: Test

on: [push]

jobs:
  fastapi:
    runs-on: ubuntu-latest
    # if: "contains(github.event.head_commit.message, 'FASTAPI: ')"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install cookiecutter
      run: |
        pip install cookiecutter
    - name: Test generate
      run: |
        cookiecutter --no-input fastapi -o target
```
 Who can help me to resolve this problem?

**Comment by pergpau** [comment] 2020-10-14 09:11
Same problem on Ubuntu 20.04. Workflow works fine on Github Actions, but fail with same error using act.

**Comment by davidjmeyer** [comment] 2020-10-15 14:34
I also have this problem, it appears to be a duplicate of #251. As mentioned on that issue, try using the alternative runner image with one of the following flags depending on which image you've specified in your workflow.

`-P ubuntu-latest=nektos/act-environments-ubuntu:18.04`
or
`-P ubuntu-18.04=nektos/act-environments-ubuntu:18.04`

**Comment by magiskboy** [comment] 2020-10-17 08:56
this problem was solved 👍 thank you @davidjmeyer

**Closed** 2020-10-17 08:56 UTC
