### ISSUE TITLE
Support loading of actions from .github/workflows/

### ISSUE THREAD

**Issue by alandtse** [nektos/act#79] opened 2019-09-22 09:57 UTC
It looks like the use of .github/main.workflow is deprecated now that [actions are moving to YAML](https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax). It'd be nice to support the new format as my newer repos with Actions does not create main.workflow anymore.

**Comment by maxheld83** [comment] 2019-09-28 19:29
this is a duplicate of #74, right?

**Comment by alandtse** [comment] 2019-09-28 22:49
This could be a subset #74.  act currently expects a `main.workflow` file to run so it's not usable by anyone who just started with Github actions and doesn't know the history. #74 seemed to be more about changing from HCL to YAML and didn't immediately strike me as related.

**Comment by novoxudonoser** [comment] 2019-10-06 20:42
+1 voting for this. In all my github repos only YAML actions used.

**Comment by cplee** [comment] 2019-10-07 14:51
Closing this as we are tracking this work in #74

**Closed by cplee** 2019-10-07 14:51 UTC
