### ISSUE TITLE
Inputs not evaluated for `uses: ./path`

### ISSUE THREAD

**Issue by Beanow** [nektos/act#166] opened 2020-03-19 13:49 UTC
Using the relative path references:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-action-in-the-same-repository-as-the-workflow

The inputs are not evaluated.
(No check for required, no renaming, no defaults)

Tried in this repo.
https://github.com/vsoch/cred-action/commit/3ecdb0d8fb37a8e2d4ba954a96a50ad38a676fc4

Where the real action passes, but `act -j smoke-env` fails.

```
[Integration tests/Smoke ENV] ⭐  Run Show diff
| --- expected.txt	2020-03-19 13:46:57.782507156 +0000
| +++ actual.txt	2020-03-19 13:46:58.106500991 +0000
| @@ -11,11 +11,11 @@
|  INPUT_TARGET=docs
|  INPUT_WEIGHTS=.github/weights.json
|  INPUT_PROJECT=@sourcecred
| -INPUT_PROJECT_FILE=.github/github.json
| -INPUT_SCORES_JSON=scores.json
| +INPUT_PROJECT_FILE=
| +INPUT_SCORES_JSON=
|  INPUT_AUTOMATED=true
| -INPUT_BRANCH_AGAINST=master
| -INPUT_TEST_RUN=true
| +INPUT_BRANCH_AGAINST=
| +INPUT_TEST_RUN=
|  
|  # SourceCred known parameters
|  SOURCECRED_DIRECTORY=/data
[Integration tests/Smoke ENV]   ❌  Failure - Show diff
```

**Comment by cplee** [comment] 2020-04-16 23:19
duplicate of #185

**Closed by cplee** 2020-04-16 23:19 UTC
Labels: area/action, kind/bug
