### ISSUE TITLE
Is runs-on ignored?

### ISSUE THREAD

**Issue by clog-rocks** [nektos/act#106] opened 2020-02-26 09:46 UTC
I am getting my workflow run on node image, even though it requires ubuntu:
```
❯ act
[Foo/build] 🚀  Start image=node:12.6-buster-slim
[Foo/build]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Foo/build]   🐳  docker cp src=/Users/foo/Sites/Foo/. dst=/github/workspace
[Foo/build] ⭐  Run Install MySQL Client
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:5 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [181 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7380 B]
Fetched 8331 kB in 3s (2453 kB/s)
Reading package lists... Done
Building dependency tree       !
Reading state information... Done
| 35 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       !
Reading state information... Done
| Package libmysqlclient-dev is not available, but is referred to by another package.
| This may mean that the package is missing, has been obsoleted, or
| is only available from another source
| However the following packages replace it:
|   libmariadb-dev-compat libmariadb-dev
|
| Package mysql-client-5.7 is not available, but is referred to by another package.
| This may mean that the package is missing, has been obsoleted, or
| is only available from another source
| However the following packages replace it:
|   mariadb-server-core-10.3 mariadb-client-10.3
|
| E: Package 'mysql-client-5.7' has no installation candidate
| E: Package 'libmysqlclient-dev' has no installation candidate
[Foo/build]   ❌  Failure - Install MySQL Client
Error: exit with `FAILURE`: 100
```

This is stripped down workflow:
```
❯ cat .github/workflows/foo.yml
name: Foo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install MySQL Client
      run: |
        apt update
        apt install mysql-client-5.7 libmysqlclient-dev
```

**Comment by cplee** [comment] 2020-02-26 19:08
See here: https://github.com/nektos/act#runners

You can customize the image that is used for each `runs-on`

**Comment by cplee** [comment] 2020-03-02 16:19
Closing this as a duplicate of #107

**Closed by cplee** 2020-03-02 16:19 UTC
Labels: area/runner, kind/question, meta/duplicate

**Comment by ernstki** [comment] 2025-08-03 01:41
> See here: https://github.com/nektos/act#runners
> 
> You can customize the image that is used for each `runs-on`

This appears to be https://nektosact.com/usage/runners.html now.

If I'm translating "you can customize the image" correctly, that simply means you can specify it at runtime with `-P`?

```bash
act -P ubuntu-18.04=my-local-ubuntu:18.04
```

In any event, thanks for a pointer in the right direction, it was key.
