### ISSUE TITLE
Workflow fails from second time because dependencies are already installed

### ISSUE THREAD

**Issue by vibin** [nektos/act#239] opened 2020-05-16 09:45 UTC
I have the below job as part of a workflow.
```yaml
- name: Install sdkman, kotlin, kscript
  if: steps.prereq.outputs.triggered == 'true'
  run: |
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install kotlin
    sdk install kscript
```
This ran fine during the first execution of "act issue_comment -e action-sample.json --verbose -P ubuntu-latest=nektos/act-environments-ubuntu:18.04". From the second time, I keep seeing errors "Previous installation of sdkman found. kotlin 1.3.72 is already installed", etc.

I've tried docker-kill and docker-rm'ing the containers but no luck. I'm not using the "--reuse" swtich.

**Comment by vibin** [comment] 2020-05-19 11:02
Probably a dupe of #237

**Comment by cplee** [comment] 2020-05-20 15:36
closing as duplicate of #237

**Closed by cplee** 2020-05-20 15:36 UTC
Labels: meta/duplicate
