### ISSUE TITLE
Enhancement: use podman as executor

### ISSUE THREAD

**Issue by drahnr** [nektos/act#553] opened 2021-03-05 16:58 UTC
## Describe feature

Instead of requiring a running and functional docker setup, running (rootless) podman might give you a usability edge.

**Comment by catthehacker** [comment] 2021-03-05 17:12
Duplicate of #303, #414

**Comment by drahnr** [comment] 2021-03-05 17:20
Those are both closed.

**Comment by catthehacker** [comment] 2021-03-05 17:29
@drahnr they are closed because there is no one available to implement such feature, same would happen with this issue, it would get stale and closed by bot. Feel free to open draft/PR with `podman` support.

**Closed** 2021-03-05 17:46 UTC
Labels: kind/feature-request

**Comment by anthr76** [comment] 2021-03-11 23:23
Sad to see no interest of an implementation for this.

**Comment by abitrolly** [comment] 2021-04-11 05:02
There is interested. Just no money to spend a week or two for hacking this feature,

**Comment by Diliz** [comment] 2021-09-20 10:03
In #303 , last message seems to be what you're seeking @drahnr : https://github.com/nektos/act/issues/303#issuecomment-882069025
