### ISSUE TITLE
Issue: Failure - actions/checkout@v2

### ISSUE THREAD

**Issue by Paultje52** [nektos/act#704] opened 2021-05-24 18:39 UTC
## Act version
```none
Act version 0.2.22
```

## Expected behaviour
It should pass the actions/checkout@v2, by copying all the files and puting them in the docket container.

## Actual behaviour
It throws the error `Input required and not supplied: token`

## Workflow and/or repository

<details>
  <summary>Workflow</summary>

```yml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, Rewrite ]
  pull_request:
    branches: [ master, Rewrite ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd syncbox-frontend && npm ci
    - run: cd syncbox-frontend && npm run build --if-present

```

</details>

## `act` output

<details>
  <summary>Log</summary>

```none
time="2021-05-24T20:35:04+02:00" level=debug msg="Loading environment from C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.env"
time="2021-05-24T20:35:04+02:00" level=debug msg="Loading secrets from C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.secrets"
time="2021-05-24T20:35:04+02:00" level=debug msg="Loading workflows from 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.github\\workflows'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Loading workflows recursively"
time="2021-05-24T20:35:04+02:00" level=debug msg="Found workflow 'front-end.test.yml' in 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.github\\workflows\\front-end.test.yml'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reading workflow 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.github\\workflows\\front-end.test.yml'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Correcting if statements 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.github\\workflows\\front-end.test.yml'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Planning event: push"
time="2021-05-24T20:35:04+02:00" level=debug msg="Loading slug from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:04+02:00" level=debug msg="Loading revision from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:04+02:00" level=debug msg="HEAD points to '15f1d59da814db9c6649cb2b9dba61f7efcbaad6'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/heads/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/heads/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/remotes/origin/HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/remotes/origin/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/remotes/origin/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:04+02:00" level=debug msg="using github ref: refs/heads/Rewrite"
time="2021-05-24T20:35:04+02:00" level=debug msg="context env => map[ACT:true]"
[Node.js CI/build] 🧪  Matrix: map[node-version:12.x]
[Node.js CI/build] 🚀  Start image=catthehacker/ubuntu:act-latest
time="2021-05-24T20:35:04+02:00" level=debug msg="Loading slug from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:04+02:00" level=debug msg="Loading revision from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:04+02:00" level=debug msg="HEAD points to '15f1d59da814db9c6649cb2b9dba61f7efcbaad6'"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/heads/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/heads/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/remotes/origin/HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/remotes/origin/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=refs/remotes/origin/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:04+02:00" level=debug msg="Reference: name=HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:04+02:00" level=debug msg="using github ref: refs/heads/Rewrite"
[Node.js CI/build]   🐳  docker pull catthehacker/ubuntu:act-latest
time="2021-05-24T20:35:04+02:00" level=debug msg="Image exists? true"
[Node.js CI/build] Removed container: 65a2784f73ff09dabd68868cd5afed86a4657feef663a2131901c3ed8431224d
[Node.js CI/build]   🐳  docker volume rm act-Node-js-CI-build
[Node.js CI/build]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Node.js CI/build] Created container name=act-Node-js-CI-build id=8cd3c5329fe09a53894dd90a22a3c323db3435824157c452b927d9eaf998acd2 from image catthehacker/ubuntu:act-latest (platform: )
[Node.js CI/build] ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_TEMP=/tmp]
[Node.js CI/build]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Node.js CI/build] Starting container: 8cd3c5329fe09a53894dd90a22a3c323db3435824157c452b927d9eaf998acd2
[Node.js CI/build] Started container: 8cd3c5329fe09a53894dd90a22a3c323db3435824157c452b927d9eaf998acd2
time="2021-05-24T20:35:09+02:00" level=debug msg="Writing entry to tarball workflow/event.json len:2"
time="2021-05-24T20:35:09+02:00" level=debug msg="Writing entry to tarball workflow/envs.txt len:0"
time="2021-05-24T20:35:09+02:00" level=debug msg="Writing entry to tarball workflow/paths.txt len:0"
[Node.js CI/build] Extracting content to '/tmp/'
time="2021-05-24T20:35:09+02:00" level=debug msg="Loading slug from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:09+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:09+02:00" level=debug msg="Loading revision from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:09+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:09+02:00" level=debug msg="HEAD points to '15f1d59da814db9c6649cb2b9dba61f7efcbaad6'"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/heads/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/heads/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/remotes/origin/HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/remotes/origin/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/remotes/origin/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:09+02:00" level=debug msg="using github ref: refs/heads/Rewrite"
time="2021-05-24T20:35:09+02:00" level=debug msg="Loading slug from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:09+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:09+02:00" level=debug msg="Loading revision from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:09+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:09+02:00" level=debug msg="HEAD points to '15f1d59da814db9c6649cb2b9dba61f7efcbaad6'"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/heads/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/heads/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/remotes/origin/HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/remotes/origin/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/remotes/origin/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:09+02:00" level=debug msg="using github ref: refs/heads/Rewrite"
time="2021-05-24T20:35:09+02:00" level=debug msg="context env => map[ACT:true AGENT_TOOLSDIRECTORY:/opt/hostedtoolcache DEPLOYMENT_BASEPATH:/opt/runner IMAGE_OS:ubuntu20 ImageOS:ubuntu20 LSB_RELEASE:20.04 PATH:\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin\" RUNNER_USER:root RUN_TOOL_CACHE:/opt/hostedtoolcache USER:root]"
time="2021-05-24T20:35:09+02:00" level=debug msg="context env => map[ACT:true AGENT_TOOLSDIRECTORY:/opt/hostedtoolcache CI:true DEPLOYMENT_BASEPATH:/opt/runner GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/tmp/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/tmp/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/tmp/workflow/paths.txt GITHUB_REF:refs/heads/Rewrite GITHUB_REPOSITORY:Paultje52/SyncBox GITHUB_REPOSITORY_OWNER:Paultje52 GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:15f1d59da814db9c6649cb2b9dba61f7efcbaad6 GITHUB_TOKEN: GITHUB_WORKFLOW:Node.js CI GITHUB_WORKSPACE:/mnt/c/Users/Paul/Desktop/Prive/NodeJS/Websites/SyncBox IMAGE_OS:ubuntu20 ImageOS:ubuntu20 LSB_RELEASE:20.04 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: RUNNER_USER:root RUN_TOOL_CACHE:/opt/hostedtoolcache USER:root]"
[Node.js CI/build] setupEnv => map[ACT:true AGENT_TOOLSDIRECTORY:/opt/hostedtoolcache CI:true DEPLOYMENT_BASEPATH:/opt/runner GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/tmp/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/tmp/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/tmp/workflow/paths.txt GITHUB_REF:refs/heads/Rewrite GITHUB_REPOSITORY:Paultje52/SyncBox GITHUB_REPOSITORY_OWNER:Paultje52 GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:15f1d59da814db9c6649cb2b9dba61f7efcbaad6 GITHUB_TOKEN: GITHUB_WORKFLOW:Node.js CI GITHUB_WORKSPACE:/mnt/c/Users/Paul/Desktop/Prive/NodeJS/Websites/SyncBox IMAGE_OS:ubuntu20 ImageOS:ubuntu20 LSB_RELEASE:20.04 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: RUNNER_USER:root RUN_TOOL_CACHE:/opt/hostedtoolcache USER:root]
[Node.js CI/build] ⭐  Run actions/checkout@v2
time="2021-05-24T20:35:09+02:00" level=debug msg="Loading slug from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:09+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:09+02:00" level=debug msg="Loading revision from git directory 'C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox\\.git'"
time="2021-05-24T20:35:09+02:00" level=debug msg="Found revision: 15f1d59da814db9c6649cb2b9dba61f7efcbaad6\n"
time="2021-05-24T20:35:09+02:00" level=debug msg="HEAD points to '15f1d59da814db9c6649cb2b9dba61f7efcbaad6'"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/heads/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/heads/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/remotes/origin/HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/remotes/origin/Rewrite sha=15f1d59da814db9c6649cb2b9dba61f7efcbaad6"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=refs/remotes/origin/master sha=ebdeea4c86b7e565c92403cd6b2aafd6ac9636cb"
time="2021-05-24T20:35:09+02:00" level=debug msg="Reference: name=HEAD sha=0000000000000000000000000000000000000000"
time="2021-05-24T20:35:09+02:00" level=debug msg="using github ref: refs/heads/Rewrite"
[Node.js CI/build]   ☁  git clone 'https://github.com/actions/checkout' # ref=v2
[Node.js CI/build]   cloning https://github.com/actions/checkout to C:\Users\Paul\.cache\act/actions-checkout@v2
[Node.js CI/build] Unable to pull refs/heads/v2: worktree contains unstaged changes
[Node.js CI/build] Cloned https://github.com/actions/checkout to C:\Users\Paul\.cache\act/actions-checkout@v2
[Node.js CI/build] Checked out v2
time="2021-05-24T20:35:10+02:00" level=debug msg="Read action &{Checkout  Checkout a Git repository at a particular version map[clean:{Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching false true} fetch-depth:{Number of commits to fetch. 0 indicates all history for all branches and tags. false 1} lfs:{Whether to download Git-LFS files false false} path:{Relative path under $GITHUB_WORKSPACE to place the repository false } persist-credentials:{Whether to configure the token or SSH key with the local git config false true} ref:{The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.\n false } repository:{Repository name with owner. For example, actions/checkout false ${{ github.repository }}} ssh-key:{SSH key used to fetch the repository. The SSH key is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the SSH key.\n\nWe recommend using a service account with the least permissions necessary.\n\n[Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)\n false } ssh-known-hosts:{Known hosts in addition to the user and global host key database. The public SSH keys for a host may be obtained using the utility `ssh-keyscan`. For example, `ssh-keyscan github.com`. The public key for github.com is always implicitly added.\n false } ssh-strict:{Whether to perform strict host key checking. When true, adds the options `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH command line. Use the input `ssh-known-hosts` to configure additional hosts.\n false true} submodules:{Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules.\n\nWhen the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are converted to HTTPS.\n false false} token:{Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT.\n\nWe recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary.\n\n[Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)\n false ${{ github.token }}}] map[] {node12 map[] dist/index.js  [] [] []} { }} from 'C:\\Users\\Paul\\.cache\\act\\actions-checkout@v2\\action.yml'"
time="2021-05-24T20:35:10+02:00" level=debug msg="About to run action &{Checkout  Checkout a Git repository at a particular version map[clean:{Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching false true} fetch-depth:{Number of commits to fetch. 0 indicates all history for all branches and tags. false 1} lfs:{Whether to download Git-LFS files false false} path:{Relative path under $GITHUB_WORKSPACE to place the repository false } persist-credentials:{Whether to configure the token or SSH key with the local git config false true} ref:{The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.\n false } repository:{Repository name with owner. For example, actions/checkout false ${{ github.repository }}} ssh-key:{SSH key used to fetch the repository. The SSH key is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the SSH key.\n\nWe recommend using a service account with the least permissions necessary.\n\n[Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)\n false } ssh-known-hosts:{Known hosts in addition to the user and global host key database. The public SSH keys for a host may be obtained using the utility `ssh-keyscan`. For example, `ssh-keyscan github.com`. The public key for github.com is always implicitly added.\n false } ssh-strict:{Whether to perform strict host key checking. When true, adds the options `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH command line. Use the input `ssh-known-hosts` to configure additional hosts.\n false true} submodules:{Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules.\n\nWhen the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are converted to HTTPS.\n false false} token:{Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT.\n\nWe recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary.\n\n[Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)\n false ${{ github.token }}}] map[] {node12 map[] dist/index.js  [] [] []} { }}"
time="2021-05-24T20:35:10+02:00" level=debug msg="Evaluating 'github['token']' instead of 'github.token'"
time="2021-05-24T20:35:10+02:00" level=debug msg="Evaluating 'github['repository']' instead of 'github.repository'"
time="2021-05-24T20:35:10+02:00" level=debug msg="type=3 actionDir=C:\\Users\\Paul\\.cache\\act/actions-checkout@v2 actionPath= Workdir=C:\\Users\\Paul\\Desktop\\Prive\\NodeJS\\Websites\\SyncBox ActionCacheDir=C:\\Users\\Paul\\.cache\\act actionName=actions-checkout@v2 containerActionDir=/mnt/c/Users/Paul/Desktop/Prive/NodeJS/Websites/SyncBox/_actions/actions-checkout@v2"
time="2021-05-24T20:35:10+02:00" level=debug msg="Removing C:\\Users\\Paul\\.cache\\act/actions-checkout@v2/.gitignore before docker cp"
[Node.js CI/build]   🐳  docker cp src=C:\Users\Paul\.cache\act/actions-checkout@v2/ dst=/mnt/c/Users/Paul/Desktop/Prive/NodeJS/Websites/SyncBox/_actions/actions-checkout@v2/
[Node.js CI/build] Exec command '[mkdir -p /mnt/c/Users/Paul/Desktop/Prive/NodeJS/Websites/SyncBox/_actions/actions-checkout@v2/]'
time="2021-05-24T20:35:11+02:00" level=debug msg="Writing tarball C:\\Users\\Paul\\AppData\\Local\\Temp\\act200790799 from C:\\Users\\Paul\\.cache\\act/actions-checkout@v2/"
time="2021-05-24T20:35:11+02:00" level=debug msg="Stripping prefix:C:\\Users\\Paul\\.cache\\act\\actions-checkout@v2\\ src:C:\\Users\\Paul\\.cache\\act/actions-checkout@v2/"
[Node.js CI/build] Extracting content from 'C:\Users\Paul\AppData\Local\Temp\act200790799' to '/mnt/c/Users/Paul/Desktop/Prive/NodeJS/Websites/SyncBox/_actions/actions-checkout@v2/'
time="2021-05-24T20:35:11+02:00" level=debug msg="executing remote job container: [node /mnt/c/Users/Paul/Desktop/Prive/NodeJS/Websites/SyncBox/_actions/actions-checkout@v2/dist/index.js]"
[Node.js CI/build] Exec command '[node /mnt/c/Users/Paul/Desktop/Prive/NodeJS/Websites/SyncBox/_actions/actions-checkout@v2/dist/index.js]'
[Node.js CI/build]   ❓  ::save-state name=isPost,::true
[Node.js CI/build]   💬  ::debug::GITHUB_WORKSPACE = '/mnt/c/Users/Paul/Desktop/Prive/NodeJS/Websites/SyncBox'
[Node.js CI/build]   💬  ::debug::qualified repository = 'Paultje52/SyncBox'
[Node.js CI/build]   💬  ::debug::ref = 'refs/heads/Rewrite'
[Node.js CI/build]   💬  ::debug::commit = '15f1d59da814db9c6649cb2b9dba61f7efcbaad6'
[Node.js CI/build]   💬  ::debug::clean = true
[Node.js CI/build]   💬  ::debug::fetch depth = 1
[Node.js CI/build]   💬  ::debug::lfs = false
[Node.js CI/build]   💬  ::debug::submodules = false
[Node.js CI/build]   💬  ::debug::recursive submodules = false
[Node.js CI/build]   ❗  ::error::Input required and not supplied: token
[Node.js CI/build]   ❌  Failure - actions/checkout@v2
time="2021-05-24T20:35:12+02:00" level=debug msg="exit with `FAILURE`: 1"
time="2021-05-24T20:35:12+02:00" level=debug msg="exit with `FAILURE`: 1"
time="2021-05-24T20:35:12+02:00" level=debug msg="exit with `FAILURE`: 1"
time="2021-05-24T20:35:12+02:00" level=debug msg="exit with `FAILURE`: 1"
Error: exit with `FAILURE`: 1
```

</details>

## Also tried
I also tried changing the `uses: actions/checkout@v2` to this, but I get the same error.
```yml
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}
```

**Comment by catthehacker** [comment] 2021-05-24 20:26
Duplicate of #678

**Closed by catthehacker** 2021-05-24 20:26 UTC
Labels: kind/bug, meta/duplicate
