### ISSUE TITLE
Issue: containers without node do not work

### ISSUE THREAD

**Issue by hexmode** [nektos/act#879] opened 2021-11-13 23:44 UTC
## System information

- Operating System: linux centos 8 stream
- Architecture: x64
- Apple M1: no
- Docker version:  20.10.10
- Docker image used in `act`: nektos/act-environments-ubuntu:18.04
- `act` version: 0.2.24

## Expected behaviour

Should successfully check out nektos/act

## Actual behaviour

Fails

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```yaml
name: CI

on: push

jobs:
  demo:
    runs-on: ubuntu-18.04
    container: mediawiki:1.35
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nektos/act
```

</details>

## Steps to reproduce

1. `./act -W workflow.yml` 

## `act` output

<details>
  <summary>Log</summary>

```none
DEBU[0000] Loading environment from /home/mah/.env      
DEBU[0000] Loading secrets from /home/mah/.secrets      
DEBU[0000] Loading workflow '/home/mah/tmp.yml'         
DEBU[0000] Reading workflow '/home/mah/tmp.yml'         
DEBU[0000] Correcting if statements '/home/mah/tmp.yml' 
DEBU[0000] Planning event: push                         
WARN[0000] unable to get git repo: unable to find git repo 
WARN[0000] unable to get git revision: unable to find git repo 
WARN[0000] unable to get git ref: unable to find git repo 
DEBU[0000] context env => map[ACT:true]                 
DEBU[0000] context needs => map[]                       
[CI/demo] 🚀  Start image=mediawiki:1.35
WARN[0000] unable to get git repo: unable to find git repo 
WARN[0000] unable to get git revision: unable to find git repo 
WARN[0000] unable to get git ref: unable to find git repo 
[CI/demo]   🐳  docker pull mediawiki:1.35
DEBU[0000] Image exists? true                           
[CI/demo] Removed container: 4c60987fc2b0d2d90dbc35e94b7b8c1395fdabb68a8aa4be61cb1c91f085f77f
[CI/demo]   🐳  docker volume rm act-CI-demo
[CI/demo]   🐳  docker create image=mediawiki:1.35 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/demo] Created container name=act-CI-demo id=230a07f6ea6761a1bb577c1a2b0cf00b0101626a5498193fd344c7b3d7e14c56 from image mediawiki:1.35 (platform: )
[CI/demo] ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_TEMP=/tmp]
[CI/demo]   🐳  docker run image=mediawiki:1.35 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/demo] Starting container: 230a07f6ea6761a1bb577c1a2b0cf00b0101626a5498193fd344c7b3d7e14c56
[CI/demo] Started container: 230a07f6ea6761a1bb577c1a2b0cf00b0101626a5498193fd344c7b3d7e14c56
[CI/demo]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[CI/demo] Exec command '[mkdir -m 0777 -p /var/run/act]'
DEBU[0001] Writing entry to tarball workflow/event.json len:2 
DEBU[0001] Writing entry to tarball workflow/envs.txt len:0 
DEBU[0001] Writing entry to tarball workflow/paths.txt len:0 
[CI/demo] Extracting content to '/var/run/act/'
WARN[0001] unable to get git repo: unable to find git repo 
WARN[0001] unable to get git revision: unable to find git repo 
WARN[0001] unable to get git ref: unable to find git repo 
WARN[0001] unable to get git repo: unable to find git repo 
WARN[0001] unable to get git revision: unable to find git repo 
WARN[0001] unable to get git ref: unable to find git repo 
DEBU[0001] context env => map[ACT:true]                 
DEBU[0001] context needs => map[]                       
WARN[0001] unable to get git repo: unable to find git repo 
WARN[0001] unable to get git revision: unable to find git repo 
WARN[0001] unable to get git ref: unable to find git repo 
DEBU[0001] context env => map[ACT:true]                 
DEBU[0001] context needs => map[]                       
DEBU[0001] context env => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:demo GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF: GITHUB_REPOSITORY: GITHUB_REPOSITORY_OWNER: GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA: GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/home/mah INPUT_REPOSITORY:nektos/act ImageOS:ubuntu18 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID:] 
[CI/demo] setupEnv => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:demo GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF: GITHUB_REPOSITORY: GITHUB_REPOSITORY_OWNER: GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA: GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/home/mah INPUT_REPOSITORY:nektos/act ImageOS:ubuntu18 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID:]
[CI/demo] ⭐  Run actions/checkout@v2
WARN[0001] unable to get git repo: unable to find git repo 
WARN[0001] unable to get git revision: unable to find git repo 
WARN[0001] unable to get git ref: unable to find git repo 
INFO[0001]   ☁  git clone 'https://github.com/actions/checkout' # ref=v2 
DEBU[0001]   cloning https://github.com/actions/checkout to /home/mah/.cache/act/actions-checkout@v2 
DEBU[0002] Unable to pull refs/heads/v2: worktree contains unstaged changes 
DEBU[0002] Cloned https://github.com/actions/checkout to /home/mah/.cache/act/actions-checkout@v2 
DEBU[0002] Checked out v2                               
DEBU[0002] Read action &{Checkout  Checkout a Git repository at a particular version map[clean:{Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching false true} fetch-depth:{Number of commits to fetch. 0 indicates all history for all branches and tags. false 1} lfs:{Whether to download Git-LFS files false false} path:{Relative path under $GITHUB_WORKSPACE to place the repository false } persist-credentials:{Whether to configure the token or SSH key with the local git config false true} ref:{The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
 false } repository:{Repository name with owner. For example, actions/checkout false ${{ github.repository }}} ssh-key:{SSH key used to fetch the repository. The SSH key is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the SSH key.

We recommend using a service account with the least permissions necessary.

[Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
 false } ssh-known-hosts:{Known hosts in addition to the user and global host key database. The public SSH keys for a host may be obtained using the utility `ssh-keyscan`. For example, `ssh-keyscan github.com`. The public key for github.com is always implicitly added.
 false } ssh-strict:{Whether to perform strict host key checking. When true, adds the options `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH command line. Use the input `ssh-known-hosts` to configure additional hosts.
 false true} submodules:{Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules.

When the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are converted to HTTPS.
 false false} token:{Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT.

We recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary.

[Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
 false ${{ github.token }}}] map[] {node12 map[] dist/index.js  [] [] []} { }} from 'Unknown' 
DEBU[0002] About to run action &{Checkout  Checkout a Git repository at a particular version map[clean:{Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching false true} fetch-depth:{Number of commits to fetch. 0 indicates all history for all branches and tags. false 1} lfs:{Whether to download Git-LFS files false false} path:{Relative path under $GITHUB_WORKSPACE to place the repository false } persist-credentials:{Whether to configure the token or SSH key with the local git config false true} ref:{The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
 false } repository:{Repository name with owner. For example, actions/checkout false ${{ github.repository }}} ssh-key:{SSH key used to fetch the repository. The SSH key is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the SSH key.

We recommend using a service account with the least permissions necessary.

[Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
 false } ssh-known-hosts:{Known hosts in addition to the user and global host key database. The public SSH keys for a host may be obtained using the utility `ssh-keyscan`. For example, `ssh-keyscan github.com`. The public key for github.com is always implicitly added.
 false } ssh-strict:{Whether to perform strict host key checking. When true, adds the options `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH command line. Use the input `ssh-known-hosts` to configure additional hosts.
 false true} submodules:{Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules.

When the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are converted to HTTPS.
 false false} token:{Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT.

We recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary.

[Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
 false ${{ github.token }}}] map[] {node12 map[] dist/index.js  [] [] []} { }} 
DEBU[0002] Evaluating 'github['token']' instead of 'github.token' 
DEBU[0002] type=3 actionDir=/home/mah/.cache/act/actions-checkout@v2 actionPath= Workdir=/home/mah ActionCacheDir=/home/mah/.cache/act actionName=actions-checkout@v2 containerActionDir=/var/run/act/actions/actions-checkout@v2 
DEBU[0002] Removing /home/mah/.cache/act/actions-checkout@v2/.gitignore before docker cp 
[CI/demo]   🐳  docker cp src=/home/mah/.cache/act/actions-checkout@v2/ dst=/var/run/act/actions/actions-checkout@v2/
[CI/demo]   🐳  docker exec cmd=[mkdir -p /var/run/act/actions/actions-checkout@v2/] user=
[CI/demo] Exec command '[mkdir -p /var/run/act/actions/actions-checkout@v2/]'
DEBU[0002] Writing tarball /tmp/act244190433 from /home/mah/.cache/act/actions-checkout@v2/ 
DEBU[0002] Stripping prefix:/home/mah/.cache/act/actions-checkout@v2/ src:/home/mah/.cache/act/actions-checkout@v2/ 
[CI/demo] Extracting content from '/tmp/act244190433' to '/var/run/act/actions/actions-checkout@v2/'
DEBU[0002] executing remote job container: [node /var/run/act/actions/actions-checkout@v2/dist/index.js] 
[CI/demo]   🐳  docker exec cmd=[node /var/run/act/actions/actions-checkout@v2/dist/index.js] user=
[CI/demo] Exec command '[node /var/run/act/actions/actions-checkout@v2/dist/index.js]'
| OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "node": executable file not found in $PATH: unknown
DEBU[0003] exit with `FAILURE`: 126                     
[CI/demo]   ❌  Failure - actions/checkout@v2
DEBU[0003] exit with `FAILURE`: 126                     
Error: exit with `FAILURE`: 126
```

</details>

**Comment by catthehacker** [comment] 2021-11-14 12:00
Duplicate of #732

**Closed by catthehacker** 2021-11-14 12:00 UTC
Labels: kind/bug
