### ISSUE TITLE
Issue: support node16

### ISSUE THREAD

**Issue by georgettica** [nektos/act#1059] opened 2022-03-20 06:59 UTC
the action setup-go has started using node16 https://github.com/actions/setup-go/pull/192, which breaks act
```
Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16
```

## System information

- Operating System: macOS
- Architecture: x64 (64-bit)
- Apple M1: no
- Docker version: 20.10.7
- Docker image used in `act`:
- `act` version: act version 0.2.25

## Expected behaviour

running act on:
```
- name: Setup golang
   uses: actions/setup-go@v3
```
should not fail

## Actual behaviour

```
act
...
[XXX] ⭐  Run Setup golang
INFO[0001]   ☁  git clone 'https://github.com/actions/setup-go' # ref=v3
[XXX]   ❌  Failure - Setup golang
Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16
```

## Workflow and/or repository

N/A

## `act` output
N/A

<details>
  <summary>Log</summary>

```none
[Verify URL's/Check for broken links] ⭐  Run Setup golang
DEBU[0001] Loading slug from git directory '/${REPODIR}/.git'
DEBU[0001] Found revision: 12fd31d4f17809cc0e7c256bb110339edc26ff60
DEBU[0001] Loading revision from git directory '/${REPODIR}/.git'
DEBU[0001] Found revision: 12fd31d4f17809cc0e7c256bb110339edc26ff60
DEBU[0001] HEAD points to '12fd31d4f17809cc0e7c256bb110339edc26ff60'
DEBU[0001] using github ref: ${BRANCHREF}
INFO[0001]   ☁  git clone 'https://github.com/actions/setup-go' # ref=v3
DEBU[0001]   cloning https://github.com/actions/setup-go to /Users/rong/.cache/act/actions-setup-go@v3
DEBU[0002] Cloned https://github.com/actions/setup-go to /Users/rong/.cache/act/actions-setup-go@v3
DEBU[0002] Checked out v3
DEBU[0002] Read action &{Setup Go environment GitHub Setup a Go environment and add it to the PATH map[check-latest:{Set this option to true if you want the action to always check for the latest available version that satisfies the version spec false false} go-version:{The Go version to download (if necessary) and use. Supports semver spec and ranges. false } token:{Used to pull node distributions from go-versions.  Since there's a default, this is typically not supplied by the user. false ${{ github.token }}}] map[] { map[]    [] []} { }} from 'Unknown'
DEBU[0002] The runs.using key in action.yml must be one of: [composite docker node12], got node16
[Verify URL's/Check for broken links]   ❌  Failure - Setup golang
DEBU[0002] The runs.using key in action.yml must be one of: [composite docker node12], got node16
DEBU[0002] The runs.using key in action.yml must be one of: [composite docker node12], got node16
DEBU[0002] The runs.using key in action.yml must be one of: [composite docker node12], got node16
DEBU[0002] Loading slug from git directory '/${REPODIR}/.git'
DEBU[0002] Found revision: 12fd31d4f17809cc0e7c256bb110339edc26ff60
DEBU[0002] Loading revision from git directory '/${REPODIR}/.git'
DEBU[0002] Found revision: 12fd31d4f17809cc0e7c256bb110339edc26ff60
DEBU[0002] HEAD points to '12fd31d4f17809cc0e7c256bb110339edc26ff60'
DEBU[0002] using github ref: ${BRANCHREF}
DEBU[0002] context env => map[ACT:true AGENT_TOOLSDIRECTORY:/opt/hostedtoolcache CI:true DEBIAN_FRONTEND:noninteractive DEPLOYMENT_BASEPATH:/opt/runner GITHUB_ACTION:1 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:Check for broken links GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:${BRANCHREF} GITHUB_REPOSITORY:${GITREPO} GITHUB_REPOSITORY_OWNER:georgettica GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:12fd31d4f17809cc0e7c256bb110339edc26ff60 GITHUB_TOKEN: GITHUB_WORKFLOW:Verify URL's GITHUB_WORKSPACE:/${REPODIR} IMAGE_OS:ubuntu20 ImageOS:ubuntu20 LSB_OS_VERSION:2004 LSB_RELEASE:20.04 PATH:/opt/hostedtoolcache/node/16.14.0/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: RUNNER_USER:root RUN_TOOL_CACHE:/opt/hostedtoolcache USER:root]
DEBU[0002] context needs => map[]
Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16
```

</details>

**Comment by catthehacker** [comment] 2022-03-20 14:03
Duplicate of #910

**Closed by catthehacker** 2022-03-20 14:03 UTC
Labels: kind/bug
