### ISSUE TITLE
Enhancement: Remove the one line in the readme about docker

### ISSUE THREAD

**Issue by BensonBen** [nektos/act#653] opened 2021-05-03 01:00 UTC
Docker has released a compatible version with the new M1 chips found in Macbooks. We should remove that line from the readme if it's no longer true.

If this tool won't work properly still with the new M1 chips a new compatibility note should be put in its place.

**Comment by catthehacker** [comment] 2021-05-03 01:02
duplicate of #623

**Closed by catthehacker** 2021-05-03 01:02 UTC
Labels: kind/feature-request
